/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jacky
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Password extends javax.swing.JFrame {
    public static ArrayList<String> Passwords = new ArrayList<String>();

    /**
     * Creates new form Password
     */
    public Password() {
        initComponents();

        
        GenPassButton.setEnabled(true);
        GenPassTB.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenPassLabel = new javax.swing.JLabel();
        GenPassTB = new javax.swing.JTextField();
        GenPassButton = new javax.swing.JButton();
        MaximumCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        SavePasswordButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CapitalCB = new javax.swing.JComboBox<>();
        SymbolsCB = new javax.swing.JComboBox<>();
        NumbersCB = new javax.swing.JComboBox<>();
        LowerCB = new javax.swing.JComboBox<>();
        ViewPassButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Generator");
        setResizable(false);

        GenPassLabel.setText("Generate Password:");

        GenPassTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenPassTBActionPerformed(evt);
            }
        });

        GenPassButton.setText("Generate");
        GenPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenPassButtonActionPerformed(evt);
            }
        });

        MaximumCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        MaximumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximumCBActionPerformed(evt);
            }
        });

        jLabel1.setText("Maximum Password Length:");

        SavePasswordButton.setText("Save Password");
        SavePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePasswordButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Capital Letters?");

        jLabel3.setText("Lower Case Letters?");

        jLabel4.setText("Numbers?");

        jLabel5.setText("Symbols?");

        CapitalCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));

        SymbolsCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));

        NumbersCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));

        LowerCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));

        ViewPassButton.setText("View Passwords");
        ViewPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(GenPassLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenPassTB))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewPassButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SavePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(GenPassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LowerCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CapitalCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NumbersCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SymbolsCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MaximumCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaximumCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapitalCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LowerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymbolsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumbersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenPassLabel)
                            .addComponent(GenPassTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavePasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(ViewPassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenPassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GenPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenPassButtonActionPerformed
        Random r = new Random();
        char RandomLetter;
        String RandomPassword = "";
        String Capital = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String Lower = "abcdefghijklmnopqrstuvwxyz";
        String Numbers = "1234567890";
        String Symbols = "&'*@{}[]^():,$=!><-%|+#;/?~._";
        String PasswordReq = "";
        boolean GeneratePassword = true;
        
        while (GeneratePassword == true){
            if (MaximumCB.getSelectedItem().equals("") || CapitalCB.getSelectedItem().equals("") || SymbolsCB.getSelectedItem().equals("") || NumbersCB.getSelectedItem().equals("") || LowerCB.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(rootPane, "There are boxes that are not filled in. Please fill them in.", "Missing Information Error", JOptionPane.INFORMATION_MESSAGE);
                GeneratePassword = false;
                break;
            }
            if (CapitalCB.getSelectedItem().equals("No") && SymbolsCB.getSelectedItem().equals("No") && NumbersCB.getSelectedItem().equals("No") && LowerCB.getSelectedItem().equals("No")){
                JOptionPane.showMessageDialog(rootPane, "Cannot create password with no characters. Please answer 'Yes' to at least 1 of the boxes.", "Password Generator Error", JOptionPane.INFORMATION_MESSAGE);
                GeneratePassword = false;   
                break;
            }
            if (CapitalCB.getSelectedItem().equals("Yes")){
                PasswordReq = PasswordReq + Capital;
            }
            if (SymbolsCB.getSelectedItem().equals("Yes")){
                PasswordReq = PasswordReq + Symbols;
            }
            if (NumbersCB.getSelectedItem().equals("Yes")){
                PasswordReq = PasswordReq + Numbers;
            }
            if (LowerCB.getSelectedItem().equals("Yes")){
                PasswordReq = PasswordReq + Lower;
            }
                
                int PasswordLength = Integer.parseInt((String)MaximumCB.getSelectedItem());
                for (int i = 0; i < PasswordLength; i++){
                    RandomLetter = PasswordReq.charAt(r.nextInt(PasswordReq.length()));
                    RandomPassword = RandomPassword + RandomLetter;
                }
                
                GenPassTB.setText(RandomPassword);
                break;
        
        
        }
        
        
        
    }//GEN-LAST:event_GenPassButtonActionPerformed

    private void GenPassTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenPassTBActionPerformed
        
    }//GEN-LAST:event_GenPassTBActionPerformed

    private void MaximumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximumCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaximumCBActionPerformed

    private void SavePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePasswordButtonActionPerformed
        if (GenPassTB.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "There are no passwords to save", "Password Save Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else{
            Passwords.add(GenPassTB.getText());
            
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter("SavedPasswords.txt", true));
            for (int i = 0; i < Passwords.size(); i++){
                out.write(Passwords.get(i) + "\r\n");
            }
            
            out.close();
            JOptionPane.showMessageDialog(rootPane, "Your password has been saved successfully." , "Password Saved Success", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (IOException ex) {
            Logger.getLogger(Password.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        }

    }//GEN-LAST:event_SavePasswordButtonActionPerformed

    private void ViewPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPassButtonActionPerformed
        //Disposes current form
        this.dispose();
        //Creating login link to registration object
        PasswordView Link = new PasswordView();
        //Set Registration page visible
        Link.setVisible(true);
    }//GEN-LAST:event_ViewPassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
            /* Create and display the form */
            File newFile = new File("SavedPasswords.txt");
            newFile.createNewFile(); // if file already exists will do nothing 

            
            String line;
            
            try{
                BufferedReader in = new BufferedReader(new FileReader("SavedPasswords.txt"));
                line = in.readLine();
                
                while (line != null){
                    Passwords.add(line);
                    line = in.readLine();
                }
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(Password.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CapitalCB;
    private javax.swing.JButton GenPassButton;
    private javax.swing.JLabel GenPassLabel;
    private javax.swing.JTextField GenPassTB;
    private javax.swing.JComboBox<String> LowerCB;
    private javax.swing.JComboBox<String> MaximumCB;
    private javax.swing.JComboBox<String> NumbersCB;
    private javax.swing.JButton SavePasswordButton;
    private javax.swing.JComboBox<String> SymbolsCB;
    private javax.swing.JButton ViewPassButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
